### PR TITLE
Build: Mem per thread

### PR DESCRIPTION
**Pull request by leonkakaowiec6**

### CODE REVIEW

**Review by tx1683 — APPROVED** [review]
ACK

**Review by tigusoft — APPROVED** [review]
concept ACK

**Review by tigusoft — DISMISSED** [review]
NACK,

thansk for updates, how ever:

- we should return value by echo. Instead of `EXPORT THREADS=...` just do `echo threads` . And then caller gets the value by doing:   `thr=$( pfp_util_estimate_make_threads 1024 )`

- also, right before return, make sure the threads is at least 1.  (it could be maybe 0 if there is little memory and it get's rounded down or something).  and `-j 0` to make means "as many jobs as cores" which is bad

- then any debug must be done as `echo ... >&2`

- please change syntax to  `foo=$( cmd )`  instead of current  syntax of placing cmd in back-tick instead '(' and instead ')' . It is easier to see begin and end of command.

- style/identation: in few lines there are mixes spaces/tabs, we use just tabs

**Review by robertoleksy — COMMENTED** [review]
Concept ACK

**Comment by sdf5** [comment]
concept ACK

**Pull request merged**
